name: DockerHub Build

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
  schedule:
  - cron: "30 6,12 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Set lower case repository name
        run: |
          echo "repository=${repository,,}" >> $GITHUB_ENV
        env:
          repository: '${{ github.repository }}'
      - name: Get revision
        shell: bash
        run: |
          REVISION=$(curl --silent "https://api.github.com/repos/kadena-io/chainweb-node/releases/latest" | jq -r .assets[0].name | grep -oP '(?<=.)\w+(?=.tar)')
          echo "REVISION=$REVISION"  >> $GITHUB_ENV
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.repository }}:latest
          build-args: REVISION=${{ env.REVISION }}
